# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

def fib(limit, i, j)
  return [] if (i>limit)          # base case
  return [i] + fib(limit, j, i+j) # recursive case
end

puts fib(4_000_000, 0, 1).inject(0){|sum, i| sum += (i%2==0 ? i : 0)}

# => 4613732
# real    0m0.007s
# user    0m0.004s
# sys     0m0.002s