# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

def is_triangle(x):
  # x = n(n+1)/2 => 0 = n^2 + n - 2x
  solve_quad(1, 1, -2*x)

def is_pentagonal(x):
  # x = n(3n-1)/2 => 0 = 3n^2 - n - 2x
  solve_quad(3, -1, -2*x)

def is_hexagonal(x):
  # x = n(2n-1) => 0 = 2n^2 - n - x
  solve_quad(2, -1, -x)

def solve_quad(a, b, c):
  # 0 = an^2 + bn + c
