# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
#   Triangle      T(n) = n(n+1)/2     1, 3, 6, 10, 15, ...
#   Pentagonal    P(n) = n(3n-1)/2    1, 5, 12, 22, 35, ...
#   Hexagonal     H(n) = n(2n-1)      1, 6, 15, 28, 45, ...
# It can be verified that T(285) = P(165) = H(143) = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

require './euler.rb'; include Euler

# all hexagonal numbers are also triangular
n = 144; hn = hexagonal(n)
(n += 1; hn = hexagonal(n)) while !is_pentagonal(hn)

puts hn

# => 1533776805
# real    0m0.056s
# user    0m0.053s
# sys     0m0.003s
